### PR TITLE
fix unused LCG multiplication bug

### PR DESCRIPTION
**Pull request by TheIronBorn**
Think this should do it.

### CODE REVIEW

**Comment by pitdicker** [comment]
Wow, that was a bad mistake... Thank you!

**Comment by TheIronBorn** [comment]
I've seen some people use tests like `rng::from_seed(seed).gen_iter() == test_data` to ensure the math is still correct.  Getting correct testing data would the difficulty there.  Perhaps finding data in other implementations?

**Comment by TheIronBorn** [comment]
My local benchmarks suggest the change is still an improvement in some cases
```
const RAND_BENCH_N: u64 = 100_000;
// snip
running 8 tests
test gen_u32_pcg_xsh_64_lcg     ... bench:     285,643 ns/iter (+/- 206,348) = 1400 MB/s
test gen_u32_pcg_xsh_64_lcg_new ... bench:     273,026 ns/iter (+/- 227,169) = 1465 MB/s
test gen_u32_pcg_xsl_64_lcg     ... bench:     289,645 ns/iter (+/- 74,716) = 1381 MB/s
test gen_u32_pcg_xsl_64_lcg_new ... bench:     276,146 ns/iter (+/- 98,760) = 1448 MB/s

test gen_u64_pcg_xsh_64_lcg     ... bench:     697,928 ns/iter (+/- 538,260) = 1146 MB/s
test gen_u64_pcg_xsh_64_lcg_new ... bench:     718,121 ns/iter (+/- 232,865) = 1114 MB/s
test gen_u64_pcg_xsl_64_lcg     ... bench:     637,746 ns/iter (+/- 307,252) = 1254 MB/s
test gen_u64_pcg_xsl_64_lcg_new ... bench:     688,658 ns/iter (+/- 209,762) = 1161 MB/s
```

**Comment by TheIronBorn** [comment]
Seems PCG has a whole collection of expected outputs https://github.com/imneme/pcg-cpp/tree/master/test-high/expected

**Comment by pitdicker** [comment]
To be honest my quality bar is pretty low for this repository, at least for now. My goal is to collect several small RNG's to see how they perform on benchmarks, PractRand and TestU01. If code looks plausible, it is good enough for now.

If I am done collecting, it makes sense to improve the quality of a few RNG's. Like adding tests, debug implementation, seeding, documentation / papers, and features like jumping / seeking. Maybe even code to recover the state of the RNG from the output, just to see how easily predictable they are (on aren't)  :smile:.

You have an interest in RNG's?

**Pull request merged**
